-- MySQL Script generated by MySQL Workbench
-- sáb 14 may 2022 12:01:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema viina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema viina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viina` DEFAULT CHARACTER SET utf8 ;
USE `viina` ;

-- -----------------------------------------------------
-- Table `viina`.`PopulatedPlace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viina`.`PopulatedPlace` (
  `idPopulatedPlace` INT NOT NULL,
  `geonameid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `asciiname` VARCHAR(45) NOT NULL,
  `alternated_names` VARCHAR(45) NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `feature_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPopulatedPlace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viina`.`ControlStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viina`.`ControlStatus` (
  `idPopulatedPlace` VARCHAR(45) NOT NULL,
  `PopulatedPlace_idPopulatedPlace` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `timestamp` DATE NOT NULL,
  INDEX `fk_ControlStatus_PopulatedPlace_idx` (`PopulatedPlace_idPopulatedPlace` ASC) VISIBLE,
  PRIMARY KEY (`idPopulatedPlace`),
  CONSTRAINT `fk_ControlStatus_PopulatedPlace`
    FOREIGN KEY (`PopulatedPlace_idPopulatedPlace`)
    REFERENCES `viina`.`PopulatedPlace` (`idPopulatedPlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viina`.`Temporary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viina`.`Temporary` (
  `idTemporary` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`idTemporary`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viina`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viina`.`Report` (
  `idReport` INT NOT NULL,
  `source` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `text` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `Temporary_idTemporary` INT NOT NULL,
  PRIMARY KEY (`idReport`),
  INDEX `fk_Report_Temporary1_idx` (`Temporary_idTemporary` ASC) VISIBLE,
  CONSTRAINT `fk_Report_Temporary1`
    FOREIGN KEY (`Temporary_idTemporary`)
    REFERENCES `viina`.`Temporary` (`idTemporary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viina`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viina`.`Event` (
  `idEvent` INT NOT NULL,
  `Report_idReport` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `geo_precision` VARCHAR(45) NULL,
  `geo_api` VARCHAR(45) NULL,
  PRIMARY KEY (`idEvent`),
  INDEX `fk_Event_Report1_idx` (`Report_idReport` ASC) VISIBLE,
  CONSTRAINT `fk_Event_Report1`
    FOREIGN KEY (`Report_idReport`)
    REFERENCES `viina`.`Report` (`idReport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
